In [2]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
a[:,2] 

array([ 3, 10])

In [ ]:
a = np.array([1,9,8,3])
print(a)

[1 9 8 3]


In [ ]:
a = np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int64


In [ ]:
b = np.array([1.1,2,3.2])
print(b.dtype)

float64


In [ ]:
c = np.array([(1,2,3),(4,5,6)])
print(c)

[[1 2 3]
 [4 5 6]]


In [3]:
d = np.array([
              [[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]
])
print(d.shape)
print(d)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [6]:
y=np.ones((1,2,3), dtype=np.int16)
print(y.shape)
print(y)

(1, 2, 3)
[[[1 1 1]
  [1 1 1]]]


In [7]:
e = np.array([(1,2,3), (4,5,6)])
print(e)
print(e.shape)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]
(2, 3)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [9]:
f=np.array([1,2,3])
g=np.array([4,5,6])

print('Horizontal Append: ', np.hstack((f,g)))

Horizontal Append:  [1 2 3 4 5 6]


In [10]:
print('Verical Append: ', np.vstack((f,g)))

Verical Append:  [[1 2 3]
 [4 5 6]]


In [11]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.83938885 5.32360388 4.4937921  5.08219292 5.24897112 5.70815409
 5.14759576 5.67154378 5.179356   3.83826043]


In [12]:
A = np.matrix(np.ones((4,4)))
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
np.asarray(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


In [15]:
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,14,4)

array([ 1,  5,  9, 13])

In [21]:
np.linspace(1.0, 10.0, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

In [23]:
x=np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

In [24]:
e=np.array([(4,5,6),(7,8,9)])
print(e)

[[4 5 6]
 [7 8 9]]


In [25]:
print('First row: ', e[0])

First row:  [4 5 6]


In [26]:
print(e[:2,1])

[5 8]


In [27]:
nomral_array = np.random.normal(5, 0.5, 10)


In [28]:
print(np.min(normal_array))
print(np.max(normal_array))
print(np.mean(nomral_array))
print(np.median(normal_array))
print(np.std(normal_array))

3.8382604325505616
5.708154093092072
5.09115183122721
5.163475876986222
0.5275562002986901


In [29]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f,g)

14

In [30]:
h = [[1,2],[3,4]]
i = [[5,6],[7,8]]
np.matmul(h, i)

array([[19, 22],
       [43, 50]])

In [31]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [34]:
n_array = np.array([[50,29],[30,44]])

print("Numpy Matrix is: ")
print(n_array)

det = np.linalg.det(n_array)

print("\nDeterminant of given 2x2 matrix:")
print(int(det))

Numpy Matrix is: 
[[50 29]
 [30 44]]

Determinant of given 2x2 matrix:
1330


In [36]:
mx=np.array([[1,1,1],[0,1,2],[1,5,3]])
np.linalg.matrix_rank(mx)

3

In [37]:
eigenvalues, eigenvectors = np.linalg.eig(mx)
print(eigenvalues, eigenvectors)

[ 5.52728869  0.81107958 -1.33836827] [[-0.27967764 -0.97874079 -0.0469752 ]
 [-0.3879655   0.20419215 -0.64926493]
 [-0.87821591 -0.01928803  0.75911026]]


In [39]:
gfg = np.matrix('[6,2; 3, 4]')
diag = gfg.diagonal()
print(diag)

[[6 4]]


In [40]:
gfg = np.matrix('[4,1;12,3]')
trans = gfg.transpose()
print(trans)

[[ 4 12]
 [ 1  3]]


In [42]:
gfg = np.matrix('[5,4;19,7]')
tracem = gfg.trace()
print(tracem)

[[12]]
